default: &default
  adapter:  postgresql
  host:     localhost
  username: markstephenson
  password:

development:
  <<: *default
  database: msb-member-dev

test:
  <<: *default
  database: msb-member-test
