# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f0a6f77bf65a8019c14903755489ee0f3d994c96cbbb029ac80642f998b839ed52772dfeca8a509ff95f5dc4d554a6cebaafbda32d2a063298e31952a1e77d6

test:
  secret_key_base: abe742e7aacfffa01588a9b626cd53aeee1c1f90a09fc229abb8e56bedbb89a28f4002f344efb70b926264ef439cf15a86dfb8b6efeb715bf0016a97f45ee1c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
